const { Visitor, load } = require("./visitor");
const alice = new Visitor("alice_cooper", 71, "1948 Feb 4", "08:20am", "American rock star", "Wilfred");
const bob = new Visitor("bob_marley", 36, "1945 Feb 6", "08:20am", "I am a raggae poineer!", "Wilfred");
const charlie = new Visitor("charlie_sheen", 55, "1965 Sept 3", "08:20am", "I am an American actor!", "Wilfred");
alice.save();
bob.save();
charlie.save();
load('alice cooper');
load('bob marley');
load('charlie sheen');